---
name: agda_ls
description:  Language Server for Agda
homepage: https://hackage.haskell.org/package/agda-language-server
licenses:
  - MIT
languages:
  - Agda
categories:
  - LSP

source:
  # renovate:datasource=hackage
  id: pkg:generic/agda/agda-language-server@0.2.6.3.0
  build:
    - target: unix
      run: |
        stack install agda-language-server-"$VERSION" --local-bin-path="$PWD"
      staged: false
      env:
        VERSION: "{{version}}"
      bin:
        als: als

schemas:
  lsp: "vscode:https://hackage.haskell.org/package/agda-language-server-{{version}}/src/package.yaml"

bin:
  als: "{{source.build.bin.als}}"
